// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using alisanljoj.Data;

#nullable disable

namespace alisanljoj.Migrations
{
    [DbContext(typeof(RequestContext))]
    partial class RequestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alisanljoj.Model.BtRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("AccessType2")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("BtRequest");
                });

            modelBuilder.Entity("alisanljoj.Model.FaturaRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("RequestCategory")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDepot")
                        .HasColumnType("text");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestMaterial")
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestPieces")
                        .HasColumnType("integer");

                    b.Property<string>("RequestSupplier")
                        .HasColumnType("text");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("alisanljoj.Model.HukukDurusma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<string>("BasisNo")
                        .HasColumnType("text");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("text");

                    b.Property<string>("CaseType")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientStatus")
                        .HasColumnType("text");

                    b.Property<string>("CounterpartyName")
                        .HasColumnType("text");

                    b.Property<string>("CounterpartyStatus")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<string>("Court")
                        .HasColumnType("text");

                    b.Property<string>("CourtType")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("TC")
                        .HasColumnType("integer");

                    b.Property<int?>("Time")
                        .HasColumnType("integer");

                    b.Property<int?>("Time2")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Duruşma");
                });

            modelBuilder.Entity("alisanljoj.Model.HukukSonuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<string>("BasisNo")
                        .HasColumnType("text");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("text");

                    b.Property<string>("CaseType")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientStatus")
                        .HasColumnType("text");

                    b.Property<string>("CounterpartyName")
                        .HasColumnType("text");

                    b.Property<string>("CounterpartyStatus")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<string>("Court")
                        .HasColumnType("text");

                    b.Property<string>("CourtType")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("TC")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("result")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HukukSonuc");
                });

            modelBuilder.Entity("alisanljoj.Model.ItRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("AccessType2")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("ItRequest");
                });

            modelBuilder.Entity("alisanljoj.Model.KargoRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("RequestCategory")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDepot")
                        .HasColumnType("text");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestMaterial")
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestPieces")
                        .HasColumnType("integer");

                    b.Property<string>("RequestSupplier")
                        .HasColumnType("text");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("Kargo");
                });

            modelBuilder.Entity("alisanljoj.Model.KargoYonetici", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("RequestCategory")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDepot")
                        .HasColumnType("text");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestMaterial")
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestPieces")
                        .HasColumnType("integer");

                    b.Property<string>("RequestSupplier")
                        .HasColumnType("text");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("KargoYonetici");
                });

            modelBuilder.Entity("alisanljoj.Model.LawRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveId")
                        .HasColumnType("integer");

                    b.Property<string>("BasisNo")
                        .HasColumnType("text");

                    b.Property<string>("CaseStatus")
                        .HasColumnType("text");

                    b.Property<string>("CaseType")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientStatus")
                        .HasColumnType("text");

                    b.Property<string>("CounterpartyName")
                        .HasColumnType("text");

                    b.Property<string>("CounterpartyStatus")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<string>("Court")
                        .HasColumnType("text");

                    b.Property<string>("CourtType")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("TC")
                        .HasColumnType("integer");

                    b.Property<int?>("Time")
                        .HasColumnType("integer");

                    b.Property<int?>("Time2")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LawRequest");
                });

            modelBuilder.Entity("alisanljoj.Model.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("DescriptionDeny")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionDeny2")
                        .HasColumnType("text");

                    b.Property<string>("RequestCategory")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDepot")
                        .HasColumnType("text");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestMaterial")
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestPieces")
                        .HasColumnType("integer");

                    b.Property<string>("RequestSupplier")
                        .HasColumnType("text");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("alisanljoj.Model.RequestBt", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("AccessType2")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionDeny")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionDenyIt")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("RequestBt");
                });

            modelBuilder.Entity("alisanljoj.Model.SiparisRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("RequestCategory")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDepot")
                        .HasColumnType("text");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestMaterial")
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestPieces")
                        .HasColumnType("integer");

                    b.Property<string>("RequestSupplier")
                        .HasColumnType("text");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("Sipariş");
                });

            modelBuilder.Entity("alisanljoj.Model.YoneticiRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("RequestCategory")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestDepot")
                        .HasColumnType("text");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestMaterial")
                        .HasColumnType("text");

                    b.Property<int>("RequestNo")
                        .HasColumnType("integer");

                    b.Property<string>("RequestPaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestPieces")
                        .HasColumnType("integer");

                    b.Property<string>("RequestSupplier")
                        .HasColumnType("text");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("Yonetici");
                });
#pragma warning restore 612, 618
        }
    }
}
